version: "3.7"

services:
  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - target: 9292
        published: 9292
        protocol: tcp
        mode: host
    volumes:
      - .:/app
      - gem-cache:/usr/local/bundle
    environment:
      - LANG=C.UTF-8

volumes:
  gem-cache:
