version: "3.7"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - target: 9292
        published: 9292
        protocol: tcp
        mode: host
    volumes:
      - .:/app
      - gem-cache:/usr/local/bundle
    environment:
      - LANG=C.UTF-8
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

volumes:
  postgresql-data:
  gem-cache:
